name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose up -d --build
